"""initial_schema

Revision ID: 4e10243479c7
Revises: 
Create Date: 2026-02-23 22:47:20.847647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e10243479c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_rates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'tenant_id', 'asset_id', name='uq_commission_rates_scope')
    )
    with op.batch_alter_table('commission_rates', schema=None) as batch_op:
        batch_op.create_index('ix_commission_rates_scope', ['scope', 'tenant_id', 'asset_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('asset_symbol', sa.String(), nullable=True),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_asset_symbol'), ['asset_symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_position_id'), ['position_id'], unique=False)
        batch_op.create_index('ix_events_position_ts', ['position_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_events_tenant_portfolio', ['tenant_id', 'portfolio_id'], unique=False)
        batch_op.create_index('ix_events_timestamp', ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_trace_id'), ['trace_id'], unique=False)

    op.create_table('guardrail_configs',
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('min_stock_pct', sa.Float(), nullable=False),
    sa.Column('max_stock_pct', sa.Float(), nullable=False),
    sa.Column('max_trade_pct_of_position', sa.Float(), nullable=True),
    sa.Column('max_daily_notional', sa.Float(), nullable=True),
    sa.Column('max_orders_per_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('optimization_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parameter_ranges', sa.JSON(), nullable=False),
    sa.Column('optimization_criteria', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_combinations', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('intraday_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('include_after_hours', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'running', 'completed', 'failed', 'cancelled')", name='ck_optimization_configs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optimization_configs', schema=None) as batch_op:
        batch_op.create_index('ix_optimization_configs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_optimization_configs_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_optimization_configs_status', ['status'], unique=False)

    op.create_table('order_policy_configs',
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('min_qty', sa.Float(), nullable=False),
    sa.Column('min_notional', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Float(), nullable=False),
    sa.Column('qty_step', sa.Float(), nullable=False),
    sa.Column('action_below_min', sa.String(), nullable=False),
    sa.Column('rebalance_ratio', sa.Float(), nullable=False),
    sa.Column('order_sizing_strategy', sa.String(), nullable=False),
    sa.Column('allow_after_hours', sa.Boolean(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('commission_rate_snapshot', sa.Float(), nullable=True),
    sa.Column('commission_estimated', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('broker_status', sa.String(length=50), nullable=True),
    sa.Column('submitted_to_broker_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_qty', sa.Float(), nullable=False),
    sa.Column('avg_fill_price', sa.Float(), nullable=True),
    sa.Column('total_commission', sa.Float(), nullable=False),
    sa.Column('last_broker_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('time_in_force', sa.String(length=10), nullable=False),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='ck_orders_side'),
    sa.CheckConstraint("status IN ('created', 'submitted', 'pending', 'working', 'partial', 'filled', 'rejected', 'cancelled')", name='ck_orders_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'idempotency_key', name='uq_orders_pos_idempotency')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_broker_order_id'), ['broker_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index('ix_orders_position_created_at', ['position_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_orders_tenant_portfolio', ['tenant_id', 'portfolio_id'], unique=False)

    op.create_table('portfolio_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('initial_asset_value', sa.Float(), nullable=False),
    sa.Column('initial_asset_units', sa.Float(), nullable=False),
    sa.Column('current_cash', sa.Float(), nullable=False),
    sa.Column('current_asset_value', sa.Float(), nullable=False),
    sa.Column('current_asset_units', sa.Float(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_states', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_states_active', ['is_active'], unique=False)
        batch_op.create_index('ix_portfolio_states_updated_at', ['updated_at'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('trading_state', sa.String(), nullable=False),
    sa.Column('trading_hours_policy', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_portfolios_tenant_id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index('ix_portfolios_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_portfolios_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_portfolios_user_id', ['user_id'], unique=False)

    op.create_table('position_baselines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('baseline_price', sa.Float(), nullable=False),
    sa.Column('baseline_qty', sa.Float(), nullable=False),
    sa.Column('baseline_cash', sa.Float(), nullable=False),
    sa.Column('baseline_total_value', sa.Float(), nullable=False),
    sa.Column('baseline_stock_value', sa.Float(), nullable=False),
    sa.Column('baseline_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_baselines_baseline_timestamp'), ['baseline_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_baselines_position_id'), ['position_id'], unique=False)
        batch_op.create_index('ix_position_baselines_position_timestamp', ['position_id', 'baseline_timestamp'], unique=False)

    op.create_table('position_evaluation_timeline',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('portfolio_name', sa.String(), nullable=True),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_session', sa.String(), nullable=True),
    sa.Column('evaluation_type', sa.String(), nullable=False),
    sa.Column('evaluation_seq', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('simulation_run_id', sa.String(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('last_trade_price', sa.Float(), nullable=True),
    sa.Column('best_bid', sa.Float(), nullable=True),
    sa.Column('best_ask', sa.Float(), nullable=True),
    sa.Column('official_close_price', sa.Float(), nullable=True),
    sa.Column('effective_price', sa.Float(), nullable=True),
    sa.Column('price_policy_requested', sa.String(), nullable=True),
    sa.Column('price_policy_effective', sa.String(), nullable=True),
    sa.Column('price_fallback_reason', sa.Text(), nullable=True),
    sa.Column('data_provider', sa.String(), nullable=True),
    sa.Column('is_market_hours', sa.Boolean(), nullable=False),
    sa.Column('allow_after_hours', sa.Boolean(), nullable=False),
    sa.Column('trading_hours_policy', sa.String(), nullable=True),
    sa.Column('price_validation_valid', sa.Boolean(), nullable=True),
    sa.Column('price_validation_rejections', sa.JSON(), nullable=True),
    sa.Column('price_validation_warnings', sa.JSON(), nullable=True),
    sa.Column('is_fresh', sa.Boolean(), nullable=False),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.Column('position_qty_before', sa.Float(), nullable=False),
    sa.Column('position_cash_before', sa.Float(), nullable=False),
    sa.Column('position_stock_value_before', sa.Float(), nullable=False),
    sa.Column('position_total_value_before', sa.Float(), nullable=False),
    sa.Column('position_stock_pct_before', sa.Float(), nullable=True),
    sa.Column('position_dividend_receivable_before', sa.Float(), nullable=False),
    sa.Column('cash_pct', sa.Float(), nullable=True),
    sa.Column('stock_pct', sa.Float(), nullable=True),
    sa.Column('dividend_declared', sa.Boolean(), nullable=False),
    sa.Column('dividend_ex_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dividend_pay_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dividend_rate', sa.Float(), nullable=True),
    sa.Column('dividend_gross_value', sa.Float(), nullable=True),
    sa.Column('dividend_tax', sa.Float(), nullable=True),
    sa.Column('dividend_net_value', sa.Float(), nullable=True),
    sa.Column('dividend_applied', sa.Boolean(), nullable=False),
    sa.Column('anchor_price', sa.Float(), nullable=True),
    sa.Column('pct_change_from_anchor', sa.Float(), nullable=True),
    sa.Column('pct_change_from_prev', sa.Float(), nullable=True),
    sa.Column('anchor_updated', sa.Boolean(), nullable=False),
    sa.Column('anchor_reset_old_value', sa.Float(), nullable=True),
    sa.Column('anchor_reset_reason', sa.Text(), nullable=True),
    sa.Column('trigger_up_threshold', sa.Float(), nullable=True),
    sa.Column('trigger_down_threshold', sa.Float(), nullable=True),
    sa.Column('trigger_direction', sa.String(), nullable=True),
    sa.Column('trigger_fired', sa.Boolean(), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('guardrail_min_stock_pct', sa.Float(), nullable=True),
    sa.Column('guardrail_max_stock_pct', sa.Float(), nullable=True),
    sa.Column('guardrail_max_trade_pct', sa.Float(), nullable=True),
    sa.Column('guardrail_max_orders_per_day', sa.Integer(), nullable=True),
    sa.Column('guardrail_allowed', sa.Boolean(), nullable=True),
    sa.Column('guardrail_block_reason', sa.Text(), nullable=True),
    sa.Column('order_policy_rebalance_ratio', sa.Float(), nullable=True),
    sa.Column('order_policy_commission_rate', sa.Float(), nullable=True),
    sa.Column('order_policy_min_qty', sa.Float(), nullable=True),
    sa.Column('order_policy_min_notional', sa.Float(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('action_reason', sa.Text(), nullable=True),
    sa.Column('trade_intent_qty', sa.Float(), nullable=True),
    sa.Column('trade_intent_value', sa.Float(), nullable=True),
    sa.Column('trade_intent_cash_delta', sa.Float(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=False),
    sa.Column('action_side', sa.String(), nullable=True),
    sa.Column('action_qty_raw', sa.Float(), nullable=True),
    sa.Column('action_qty_trimmed', sa.Float(), nullable=True),
    sa.Column('action_notional', sa.Float(), nullable=True),
    sa.Column('action_commission_estimated', sa.Float(), nullable=True),
    sa.Column('action_trimming_reason', sa.Text(), nullable=True),
    sa.Column('decision_allowed', sa.Boolean(), nullable=True),
    sa.Column('decision_rejections', sa.JSON(), nullable=True),
    sa.Column('decision_warnings', sa.JSON(), nullable=True),
    sa.Column('decision_explanation', sa.Text(), nullable=True),
    sa.Column('post_trade_stock_pct', sa.Float(), nullable=True),
    sa.Column('post_trade_stock_value', sa.Float(), nullable=True),
    sa.Column('post_trade_cash', sa.Float(), nullable=True),
    sa.Column('post_trade_total_value', sa.Float(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('trade_id', sa.String(), nullable=True),
    sa.Column('execution_price', sa.Float(), nullable=True),
    sa.Column('execution_qty', sa.Float(), nullable=True),
    sa.Column('execution_commission', sa.Float(), nullable=True),
    sa.Column('execution_commission_rate_effective', sa.Float(), nullable=True),
    sa.Column('execution_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('commission_value', sa.Float(), nullable=True),
    sa.Column('position_qty_after', sa.Float(), nullable=True),
    sa.Column('position_cash_after', sa.Float(), nullable=True),
    sa.Column('position_stock_value_after', sa.Float(), nullable=True),
    sa.Column('position_total_value_after', sa.Float(), nullable=True),
    sa.Column('position_stock_pct_after', sa.Float(), nullable=True),
    sa.Column('new_anchor_price', sa.Float(), nullable=True),
    sa.Column('portfolio_total_value_before', sa.Float(), nullable=True),
    sa.Column('portfolio_total_value_after', sa.Float(), nullable=True),
    sa.Column('portfolio_cash_before', sa.Float(), nullable=True),
    sa.Column('portfolio_cash_after', sa.Float(), nullable=True),
    sa.Column('portfolio_stock_value_before', sa.Float(), nullable=True),
    sa.Column('portfolio_stock_value_after', sa.Float(), nullable=True),
    sa.Column('position_weight_pct_before', sa.Float(), nullable=True),
    sa.Column('position_weight_pct_after', sa.Float(), nullable=True),
    sa.Column('evaluation_notes', sa.Text(), nullable=True),
    sa.Column('pricing_notes', sa.Text(), nullable=True),
    sa.Column('trigger_notes', sa.Text(), nullable=True),
    sa.Column('guardrail_notes', sa.Text(), nullable=True),
    sa.Column('action_notes', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('evaluation_summary', sa.Text(), nullable=True),
    sa.Column('evaluation_details', sa.JSON(), nullable=True),
    sa.Column('market_data_details', sa.JSON(), nullable=True),
    sa.Column('strategy_state_details', sa.JSON(), nullable=True),
    sa.Column('execution_details', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.CheckConstraint("action IN ('BUY', 'SELL', 'HOLD', 'SKIP')", name='ck_eval_timeline_action'),
    sa.CheckConstraint("evaluation_type IN ('DAILY_CHECK', 'PRICE_UPDATE', 'DIVIDEND', 'TRADE_INTENT', 'EXECUTION')", name='ck_eval_timeline_evaluation_type'),
    sa.CheckConstraint("market_session IN ('REGULAR', 'EXTENDED', NULL)", name='ck_eval_timeline_session'),
    sa.CheckConstraint("mode IN ('LIVE', 'SIMULATION')", name='ck_eval_timeline_mode'),
    sa.CheckConstraint("trigger_direction IN ('UP', 'DOWN', 'NONE', NULL)", name='ck_eval_timeline_trigger_dir'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position_evaluation_timeline', schema=None) as batch_op:
        batch_op.create_index('ix_eval_timeline_action', ['action'], unique=False)
        batch_op.create_index('ix_eval_timeline_dividend_applied', ['dividend_applied'], unique=False)
        batch_op.create_index('ix_eval_timeline_mode', ['mode'], unique=False)
        batch_op.create_index('ix_eval_timeline_portfolio_timestamp', ['portfolio_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_eval_timeline_position_seq', ['position_id', 'evaluation_seq'], unique=False)
        batch_op.create_index('ix_eval_timeline_position_timestamp', ['position_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_eval_timeline_simulation_run', ['simulation_run_id'], unique=False)
        batch_op.create_index('ix_eval_timeline_symbol_timestamp', ['symbol', 'timestamp'], unique=False)
        batch_op.create_index('ix_eval_timeline_tenant_portfolio', ['tenant_id', 'portfolio_id'], unique=False)
        batch_op.create_index('ix_eval_timeline_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_eval_timeline_trace_id', ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_evaluation_type'), ['evaluation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_simulation_run_id'), ['simulation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_evaluation_timeline_trade_id'), ['trade_id'], unique=False)

    op.create_table('position_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('effective_price', sa.Float(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('action_reason', sa.Text(), nullable=True),
    sa.Column('qty_before', sa.Float(), nullable=False),
    sa.Column('qty_after', sa.Float(), nullable=False),
    sa.Column('cash_before', sa.Float(), nullable=False),
    sa.Column('cash_after', sa.Float(), nullable=False),
    sa.Column('total_value_after', sa.Float(), nullable=False),
    sa.CheckConstraint("action IN ('BUY', 'SELL', 'NONE')", name='ck_position_events_action'),
    sa.CheckConstraint("event_type IN ('PRICE', 'TRIGGER', 'GUARDRAIL', 'ORDER', 'TRADE')", name='ck_position_events_event_type'),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('position_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_events_position_id'), ['position_id'], unique=False)
        batch_op.create_index('ix_position_events_position_timestamp', ['position_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('asset_symbol', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('anchor_price', sa.Float(), nullable=True),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('op_min_qty', sa.Float(), nullable=True),
    sa.Column('op_min_notional', sa.Float(), nullable=True),
    sa.Column('op_lot_size', sa.Float(), nullable=True),
    sa.Column('op_qty_step', sa.Float(), nullable=True),
    sa.Column('op_action_below_min', sa.String(), nullable=True),
    sa.Column('gr_min_stock_alloc_pct', sa.Float(), nullable=True),
    sa.Column('gr_max_stock_alloc_pct', sa.Float(), nullable=True),
    sa.Column('gr_max_orders_per_day', sa.Integer(), nullable=True),
    sa.Column('total_commission_paid', sa.Float(), nullable=False),
    sa.Column('total_dividends_received', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('RUNNING', 'PAUSED')", name='ck_positions_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('simulation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_trading_days', sa.Integer(), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('algorithm_trades', sa.Integer(), nullable=False),
    sa.Column('algorithm_pnl', sa.Float(), nullable=False),
    sa.Column('algorithm_return_pct', sa.Float(), nullable=False),
    sa.Column('algorithm_volatility', sa.Float(), nullable=False),
    sa.Column('algorithm_sharpe_ratio', sa.Float(), nullable=False),
    sa.Column('algorithm_max_drawdown', sa.Float(), nullable=False),
    sa.Column('buy_hold_pnl', sa.Float(), nullable=False),
    sa.Column('buy_hold_return_pct', sa.Float(), nullable=False),
    sa.Column('buy_hold_volatility', sa.Float(), nullable=False),
    sa.Column('buy_hold_sharpe_ratio', sa.Float(), nullable=False),
    sa.Column('buy_hold_max_drawdown', sa.Float(), nullable=False),
    sa.Column('excess_return', sa.Float(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('information_ratio', sa.Float(), nullable=False),
    sa.Column('trade_log', sa.JSON(), nullable=True),
    sa.Column('daily_returns', sa.JSON(), nullable=True),
    sa.Column('dividend_analysis', sa.JSON(), nullable=True),
    sa.Column('price_data', sa.JSON(), nullable=True),
    sa.Column('trigger_analysis', sa.JSON(), nullable=True),
    sa.Column('time_series_data', sa.JSON(), nullable=True),
    sa.Column('debug_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.create_index('ix_simulation_results_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_simulation_results_end_date', ['end_date'], unique=False)
        batch_op.create_index('ix_simulation_results_start_date', ['start_date'], unique=False)
        batch_op.create_index('ix_simulation_results_ticker', ['ticker'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('commission_rate_effective', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='ck_trades_side'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('ix_trades_order_id', ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index('ix_trades_position_executed_at', ['position_id', 'executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_trades_tenant_portfolio', ['tenant_id', 'portfolio_id'], unique=False)

    op.create_table('trading_experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('baseline_price', sa.Float(), nullable=False),
    sa.Column('baseline_shares_equivalent', sa.Float(), nullable=False),
    sa.Column('current_portfolio_value', sa.Float(), nullable=False),
    sa.Column('current_buyhold_value', sa.Float(), nullable=False),
    sa.Column('evaluation_count', sa.Integer(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('total_commission_paid', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('RUNNING', 'PAUSED', 'COMPLETED')", name='ck_trading_experiments_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_experiments', schema=None) as batch_op:
        batch_op.create_index('ix_trading_experiments_portfolio_id', ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_experiments_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_experiments_status'), ['status'], unique=False)
        batch_op.create_index('ix_trading_experiments_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('ix_trading_experiments_ticker', ['ticker'], unique=False)

    op.create_table('trigger_configs',
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('up_threshold_pct', sa.Float(), nullable=False),
    sa.Column('down_threshold_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('heatmap_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_id', sa.String(), nullable=False),
    sa.Column('x_parameter', sa.String(), nullable=False),
    sa.Column('y_parameter', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('heatmap_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['optimization_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('heatmap_data', schema=None) as batch_op:
        batch_op.create_index('ix_heatmap_data_config_id', ['config_id'], unique=False)
        batch_op.create_index('ix_heatmap_data_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_heatmap_data_metric', ['metric'], unique=False)
        batch_op.create_index('ix_heatmap_data_parameters', ['x_parameter', 'y_parameter'], unique=False)

    op.create_table('optimization_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_id', sa.String(), nullable=False),
    sa.Column('parameter_combination', sa.JSON(), nullable=False),
    sa.Column('combination_id', sa.String(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('simulation_result', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'cancelled')", name='ck_optimization_results_status'),
    sa.ForeignKeyConstraint(['config_id'], ['optimization_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optimization_results', schema=None) as batch_op:
        batch_op.create_index('ix_optimization_results_combination_id', ['combination_id'], unique=False)
        batch_op.create_index('ix_optimization_results_config_id', ['config_id'], unique=False)
        batch_op.create_index('ix_optimization_results_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_optimization_results_status', ['status'], unique=False)

    op.create_table('portfolio_config',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('trigger_up_pct', sa.Float(), nullable=False),
    sa.Column('trigger_down_pct', sa.Float(), nullable=False),
    sa.Column('min_stock_pct', sa.Float(), nullable=False),
    sa.Column('max_stock_pct', sa.Float(), nullable=False),
    sa.Column('max_trade_pct_of_position', sa.Float(), nullable=True),
    sa.Column('commission_rate_pct', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'portfolio_id'], ['portfolios.tenant_id', 'portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'portfolio_id')
    )
    with op.batch_alter_table('portfolio_config', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_config_tenant_portfolio', ['tenant_id', 'portfolio_id'], unique=False)

    op.create_table('portfolio_positions',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id', 'position_id'),
    sa.UniqueConstraint('portfolio_id', 'position_id', name='uq_portfolio_positions')
    )
    with op.batch_alter_table('portfolio_positions', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_positions_portfolio_id', ['portfolio_id'], unique=False)
        batch_op.create_index('ix_portfolio_positions_position_id', ['position_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_positions', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_positions_position_id')
        batch_op.drop_index('ix_portfolio_positions_portfolio_id')

    op.drop_table('portfolio_positions')
    with op.batch_alter_table('portfolio_config', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_config_tenant_portfolio')

    op.drop_table('portfolio_config')
    with op.batch_alter_table('optimization_results', schema=None) as batch_op:
        batch_op.drop_index('ix_optimization_results_status')
        batch_op.drop_index('ix_optimization_results_created_at')
        batch_op.drop_index('ix_optimization_results_config_id')
        batch_op.drop_index('ix_optimization_results_combination_id')

    op.drop_table('optimization_results')
    with op.batch_alter_table('heatmap_data', schema=None) as batch_op:
        batch_op.drop_index('ix_heatmap_data_parameters')
        batch_op.drop_index('ix_heatmap_data_metric')
        batch_op.drop_index('ix_heatmap_data_created_at')
        batch_op.drop_index('ix_heatmap_data_config_id')

    op.drop_table('heatmap_data')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    op.drop_table('trigger_configs')
    with op.batch_alter_table('trading_experiments', schema=None) as batch_op:
        batch_op.drop_index('ix_trading_experiments_ticker')
        batch_op.drop_index('ix_trading_experiments_tenant_id')
        batch_op.drop_index(batch_op.f('ix_trading_experiments_status'))
        batch_op.drop_index(batch_op.f('ix_trading_experiments_position_id'))
        batch_op.drop_index('ix_trading_experiments_portfolio_id')

    op.drop_table('trading_experiments')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_tenant_portfolio')
        batch_op.drop_index(batch_op.f('ix_trades_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_trades_position_id'))
        batch_op.drop_index('ix_trades_position_executed_at')
        batch_op.drop_index(batch_op.f('ix_trades_portfolio_id'))
        batch_op.drop_index('ix_trades_order_id')

    op.drop_table('trades')
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.drop_index('ix_simulation_results_ticker')
        batch_op.drop_index('ix_simulation_results_start_date')
        batch_op.drop_index('ix_simulation_results_end_date')
        batch_op.drop_index('ix_simulation_results_created_at')

    op.drop_table('simulation_results')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_positions_status'))
        batch_op.drop_index(batch_op.f('ix_positions_portfolio_id'))

    op.drop_table('positions')
    with op.batch_alter_table('position_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_events_timestamp'))
        batch_op.drop_index('ix_position_events_position_timestamp')
        batch_op.drop_index(batch_op.f('ix_position_events_position_id'))
        batch_op.drop_index(batch_op.f('ix_position_events_event_type'))

    op.drop_table('position_events')
    with op.batch_alter_table('position_evaluation_timeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_trade_id'))
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_trace_id'))
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_timestamp'))
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_symbol'))
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_source'))
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_simulation_run_id'))
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_position_id'))
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_order_id'))
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_mode'))
        batch_op.drop_index(batch_op.f('ix_position_evaluation_timeline_evaluation_type'))
        batch_op.drop_index('ix_eval_timeline_trace_id')
        batch_op.drop_index('ix_eval_timeline_timestamp')
        batch_op.drop_index('ix_eval_timeline_tenant_portfolio')
        batch_op.drop_index('ix_eval_timeline_symbol_timestamp')
        batch_op.drop_index('ix_eval_timeline_simulation_run')
        batch_op.drop_index('ix_eval_timeline_position_timestamp')
        batch_op.drop_index('ix_eval_timeline_position_seq')
        batch_op.drop_index('ix_eval_timeline_portfolio_timestamp')
        batch_op.drop_index('ix_eval_timeline_mode')
        batch_op.drop_index('ix_eval_timeline_dividend_applied')
        batch_op.drop_index('ix_eval_timeline_action')

    op.drop_table('position_evaluation_timeline')
    with op.batch_alter_table('position_baselines', schema=None) as batch_op:
        batch_op.drop_index('ix_position_baselines_position_timestamp')
        batch_op.drop_index(batch_op.f('ix_position_baselines_position_id'))
        batch_op.drop_index(batch_op.f('ix_position_baselines_baseline_timestamp'))

    op.drop_table('position_baselines')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolios_user_id')
        batch_op.drop_index('ix_portfolios_updated_at')
        batch_op.drop_index(batch_op.f('ix_portfolios_tenant_id'))
        batch_op.drop_index('ix_portfolios_created_at')

    op.drop_table('portfolios')
    with op.batch_alter_table('portfolio_states', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_states_updated_at')
        batch_op.drop_index('ix_portfolio_states_active')

    op.drop_table('portfolio_states')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_tenant_portfolio')
        batch_op.drop_index(batch_op.f('ix_orders_tenant_id'))
        batch_op.drop_index('ix_orders_position_created_at')
        batch_op.drop_index(batch_op.f('ix_orders_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_orders_broker_order_id'))

    op.drop_table('orders')
    op.drop_table('order_policy_configs')
    with op.batch_alter_table('optimization_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_optimization_configs_status')
        batch_op.drop_index('ix_optimization_configs_created_by')
        batch_op.drop_index('ix_optimization_configs_created_at')

    op.drop_table('optimization_configs')
    op.drop_table('guardrail_configs')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_trace_id'))
        batch_op.drop_index('ix_events_timestamp')
        batch_op.drop_index('ix_events_tenant_portfolio')
        batch_op.drop_index(batch_op.f('ix_events_tenant_id'))
        batch_op.drop_index('ix_events_position_ts')
        batch_op.drop_index(batch_op.f('ix_events_position_id'))
        batch_op.drop_index(batch_op.f('ix_events_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_events_asset_symbol'))

    op.drop_table('events')
    with op.batch_alter_table('commission_rates', schema=None) as batch_op:
        batch_op.drop_index('ix_commission_rates_scope')

    op.drop_table('commission_rates')
    # ### end Alembic commands ###
