# =========================
# backend/domain/ports/orders_repo.py
# =========================
from typing import Protocol, Iterable, Optional
from datetime import date, datetime
from domain.entities.order import Order


class OrdersRepo(Protocol):
    def get(self, order_id: str) -> Optional[Order]: ...
    def save(self, order: Order) -> None: ...
    def count_for_position_on_day(self, position_id: str, day: date) -> int: ...
    def list_for_position(self, position_id: str, limit: int = 100) -> Iterable[Order]: ...
    def clear(self) -> None: ...
    def count_for_position_between(
        self, position_id: str, start: datetime, end: datetime
    ) -> int: ...
