# =========================
# backend/domain/ports/positions_repo.py
# =========================

from typing import Protocol, Optional
from domain.entities.position import Position


class PositionsRepo(Protocol):
    def get(self, position_id: str) -> Optional[Position]: ...
    def create(self, ticker: str, qty: float, cash: float) -> Position: ...
    def save(self, position: Position) -> None: ...
    def delete(self, position_id: str) -> bool: ...
    def clear(self) -> None: ...
    def list_all(self) -> list[Position]: ...
