from __future__ import annotations

from typing import Protocol, Optional
from domain.entities.user import User


class UserRepo(Protocol):
    def get_by_id(self, user_id: str) -> Optional[User]: ...

    def get_by_email(self, tenant_id: str, email: str) -> Optional[User]: ...

    def get_by_email_global(self, email: str) -> Optional[User]: ...

    def create(self, user: User) -> User: ...

    def update(self, user: User) -> User: ...

    def count_by_tenant(self, tenant_id: str) -> int: ...

    def list_by_tenant(self, tenant_id: str) -> list[User]: ...

    def clear(self) -> None: ...
